### ISSUE TITLE
Result differs from the dual illumination paper

### ISSUE THREAD

**Issue by emptyarray** [pvnieo/Low-light-Image-Enhancement#2]
I have tried running the dual algorithm and comparing it to the result from the paper, but they are different.

This is the original and enhanced version from the paper:

![image](https://user-images.githubusercontent.com/1262053/106344636-c5825400-625f-11eb-925e-7d48d1de2451.png)

This is the output I get from running the dual script for this project:

![Underexposed Test_DUAL_g0 6_l0 15](https://user-images.githubusercontent.com/1262053/106344649-e5197c80-625f-11eb-9d02-8bc72401474d.png)

I am using the default parameters, `g=0.6` and `l=0.15`. The results seem more noisy and oversaturated than the results displayed in the paper, and the contrast is different.

Is there a combination of parameters that would give the same results as the paper that I can try, or is it possible that there is a bug in the algorithm? Thanks.

**Comment by pvnieo** [comment]
Hi,

Unfortunately, the original authors didn't provide their code, and I'm guessing they did some post processing they didn't describe in the paper. As far as the implementation of the proposed algorithm is concerned, it's as described in the paper, you can check it in the code.

Also, they could be using other hyper-parameters than the default one, so maybe you should try some hyper-param tuning.

Hope this answer your question!

**Comment by pvnieo** [comment]
Closing the issue, feel free to re-open it if you have any additional question!
