### ISSUE TITLE
Why does it take so long to process

### ISSUE THREAD

**Issue by JEREMY824** [pvnieo/Low-light-Image-Enhancement#7]

**Comment by pvnieo** [comment]
it's the time required to do the optimization,
feel free to suggest any modifications to make it faster!

**Comment by JEREMY824** [comment]
> it's the time required to do the optimization, feel free to suggest any modifications to make it faster!

The official code is about 0.5 seconds per image, but this code takes 9 seconds.

**Comment by pvnieo** [comment]
do you have access to the official code? or just the **compiled** version?
if it's the case, do you mind sharing it with me?

**Comment by YeolJ00** [comment]
Hi, I amd also looking forward to some speed ups.

The code here seems to be implementing equation 8 in the [LIME paper](https://ieeexplore.ieee.org/ielaam/83/7763897/7782813-aam.pdf), which is not the sped-up solver and thus slow.

Some other implementations (that I wasn't able to fully understand) use some iterative solvers which seems to solve equation 19 in the paper.

https://github.com/Henry-GongZY/Low-light-Image-Enhancement/blob/master/LIME.py
https://github.com/estija/LIME/blob/master/lime_trial.m

Can you understand these codes?

**Comment by pvnieo** [comment]
Hi @YeolJ00 

Thanks for the references, I'll take a look when I have time!

**Comment by ytmTragodie** [comment]
> do you have access to the official code? or just the **compiled** version? if it's the case, do you mind sharing it with me?
the url metioned in the paper can not be acessed
maybe this is the official demo?  
https://sites.google.com/view/xjguo/lime
but u need to ask for a permission
